sudo: required
# language: generic
services:
  - docker

before_install:
  - docker build -t marcus-almeida/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true marcus-almeida/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  # Name of the application on Elastic Beanstalk
  app: "docker-react"
  # Elastic Beanstalk environment
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-395748482621"
  # Name of the application on Elastic Beanstalk
  bucket_path: "docker-react"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
