sudo: required
# language: generic
services:
  - docker

before_install:
  - docker build -t marcus-almeida/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true marcus-almeida/docker-react npm run test

